import type { Dish } from "@/lib/types";

const now = new Date().toISOString();

export const MOCK_DISHES: Dish[] = [
  {
    id: "dish_banh_cuon",
    slug: "banh-uot-banh-cuon",
    name: "Bánh Ướt / Bánh Cuốn",
    shortDescription: "Fresh steamed rice sheets and rolls, sold by the pound.",
    longDescription:
      "Soft steamed rice sheets and bánh cuốn prepared for pickup or delivery. Sold by the pound.",
    category: "main",
    bulkDiscountTiers: [],
    priceCents: 1000,
    currency: "USD",
    status: "live",
    leadTimeDays: 1,
    isFeaturedWeek: true,
    isAnchorDish: true,
    availableFromUtc: null,
    availableToUtc: null,
    createdAtUtc: now,
    updatedAtUtc: now,
    images: [
      {
        id: "img_banh_cuon_current",
        url: "/demo/banh-cuon-demo.svg",
        altText: "Bánh ướt and bánh cuốn tray",
        sortOrder: 0,
      },
    ],
    ingredients: [
      { name: "Rice flour", isAllergen: false },
      { name: "Tapioca starch", isAllergen: false },
      { name: "Fried shallots", isAllergen: false },
      { name: "Fish sauce may be served on the side", isAllergen: true },
    ],
    dietaryTags: [{ code: "dairy_free", label: "Dairy-Free" }],
    nutrition: null,
  },
  {
    id: "dish_cha_ca",
    slug: "cha-ca",
    name: "Chả Cá",
    shortDescription: "Vietnamese fish cake, sold by the pound.",
    longDescription:
      "Savory Vietnamese fish cake with herbs and seasoning. Sold by the pound.",
    category: "main",
    bulkDiscountTiers: [],
    priceCents: 1200,
    currency: "USD",
    status: "live",
    leadTimeDays: 1,
    isFeaturedWeek: true,
    isAnchorDish: true,
    availableFromUtc: null,
    availableToUtc: null,
    createdAtUtc: now,
    updatedAtUtc: now,
    images: [
      {
        id: "img_cha_ca_current",
        url: "https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=1200&q=80",
        altText: "Vietnamese fish cake",
        sortOrder: 0,
      },
    ],
    ingredients: [
      { name: "Fish", isAllergen: true },
      { name: "Garlic", isAllergen: false },
      { name: "Black pepper", isAllergen: false },
      { name: "Fish sauce", isAllergen: true },
    ],
    dietaryTags: [{ code: "dairy_free", label: "Dairy-Free" }],
    nutrition: null,
  },
  {
    id: "dish_nem_chua",
    slug: "nem-chua",
    name: "Nem Chua",
    shortDescription: "Vietnamese cured pork, sold by the pound.",
    longDescription:
      "Tangy Vietnamese cured pork with garlic and chili notes. Sold by the pound.",
    category: "side",
    bulkDiscountTiers: [],
    priceCents: 800,
    currency: "USD",
    status: "live",
    leadTimeDays: 2,
    isFeaturedWeek: false,
    isAnchorDish: true,
    availableFromUtc: null,
    availableToUtc: null,
    createdAtUtc: now,
    updatedAtUtc: now,
    images: [
      {
        id: "img_nem_chua_current",
        url: "https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?auto=format&fit=crop&w=1200&q=80",
        altText: "Nem chua Vietnamese cured pork",
        sortOrder: 0,
      },
    ],
    ingredients: [
      { name: "Pork", isAllergen: false },
      { name: "Garlic", isAllergen: false },
      { name: "Chili", isAllergen: false },
      { name: "Black pepper", isAllergen: false },
    ],
    dietaryTags: [{ code: "dairy_free", label: "Dairy-Free" }],
    nutrition: null,
  },
  {
    id: "dish_banh_tom_chien",
    slug: "banh-tom-chien",
    name: "Bánh Tôm Chiên",
    shortDescription: "Crispy fried shrimp cake, priced per piece.",
    longDescription:
      "Crispy fried shrimp cake prepared fresh for pickup or delivery. Priced per piece.",
    category: "side",
    bulkDiscountTiers: [],
    priceCents: 100,
    currency: "USD",
    status: "live",
    leadTimeDays: 1,
    isFeaturedWeek: false,
    isAnchorDish: true,
    availableFromUtc: null,
    availableToUtc: null,
    createdAtUtc: now,
    updatedAtUtc: now,
    images: [
      {
        id: "img_banh_tom_chien_current",
        url: "https://images.unsplash.com/photo-1562967916-eb82221dfb92?auto=format&fit=crop&w=1200&q=80",
        altText: "Crispy fried shrimp cake",
        sortOrder: 0,
      },
    ],
    ingredients: [
      { name: "Shrimp", isAllergen: true },
      { name: "Sweet potato", isAllergen: false },
      { name: "Flour batter", isAllergen: true },
      { name: "Oil", isAllergen: false },
    ],
    dietaryTags: [],
    nutrition: null,
  },
];
